require('dotenv').config()
const PORT = process.env.PORT
const queueConfig = require('./config/queue')
const http = require('http')
const app = require('./app')
const server = http.createServer(app)
const initRoutes = require('./routes')
const IO = require('./sockets')(server)
app.set('io',IO)
app.use(require('body-parser').json({limit:'10mb'}))
initRoutes(app)
server.listen(PORT,() => console.log(`http://localhost:${PORT}`)) 